USE Atif

SELECT 
	WORKER_ID
	FIRST_NAME,
	LAST_NAME,
	SALARY,
	JOINING_DATE,
	DEPT_NAME		
FROM WORKER;

--1
SELECT
	MAX(SALARY) AS MaxSalary,
	MIN(SALARY) AS MinSalary
FROM WORKER

--2
SELECT FIRST_NAME,
	REVERSE(FIRST_NAME) AS FIRST_NAME_REVERSED
FROM WORKER;

--3
SELECT FIRST_NAME,
	YEAR(JOINING_DATE) AS JOINING_YEAR
FROM WORKER

--4
SELECT
	DATEDIFF(DAY, JOINING_DATE, GETDATE()) AS TOTAL_DAY
FROM WORKER

--5
--ALTER TABLE WORKER
--	ADD PROBOTION_END DATETIME
--UPDATE WORKER
--SET
--	PROBOTION_END = DATEADD(MONTH, 6, JOINING_DATE) WHERE WORKER_ID IN (1,2,3,4,5,6,7,8)
SELECT 
	WORKER_ID
	FIRST_NAME,
	LAST_NAME,
	SALARY,
	JOINING_DATE,
	DEPT_NAME,
	PROBOTION_END
FROM WORKER;

--6
SELECT
	DEPT_NAME,
	COUNT(*) AS TOTALEMPLOYEES
FROM WORKER
GROUP BY DEPT_NAME

--7
SELECT 
	FIRST_NAME,
	LAST_NAME
FROM WORKER
WHERE LEN(FIRST_NAME) = 5

--8
SELECT 
	WORKER_ID, 
	FIRST_NAME,
	LAST_NAME,
	CONVERT(INT, SALARY) AS SALARY,
	CONVERT(VARCHAR(15), JOINING_DATE, 101) AS JOINING_DATE, DEPT_NAME
FROM WORKER
