CREATE DATABASE CompanyDB;

USE CompanyDB;

CREATE TABLE WORKER
(
  WORKER_ID INT PRIMARY KEY,
  FIRST_NAME VARCHAR(50) UNIQUE,
  LAST_NAME VARCHAR(50),
  SALARY INT CHECK (SALARY > 100),
  DEPARTMENT VARCHAR(50)
);

INSERT INTO WORKER
VALUES
  (1, 'Sanjoy', 'Das', 12000, 'Admin'),
  (2, 'Rahim', 'Khan', 9000, 'HR'),
  (3, 'Karim', 'Ali', 15000, 'Admin'),
  (4, 'Asad', 'Ullah', 8000, 'IT'),
  (5, 'Nabila', 'Islam', 11000, 'HR'),
  (6, 'Rafi', 'Hasan', 20000, 'Admin'),
  (7, 'Sumi', 'Akter', 9500, 'IT'),
  (8, 'Arif', 'Hossain', 30000, 'Finance');


SELECT *
FROM WORKER;

SELECT
  WORKER_ID,
  CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULL_NAME,
  SALARY,
  DEPARTMENT
FROM WORKER
LIMIT

SELECT *
FROM WORKER
WHERE DEPARTMENT = 'Admin';

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM WORKER
WHERE SALARY > 10000;

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM WORKER
WHERE SALARY > (
    SELECT SALARY
FROM WORKER
WHERE FIRST_NAME = 'Sanjoy'
);

UPDATE WORKER
SET SALARY = 95000
WHERE WORKER_ID = 8;

DELETE FROM WORKER
WHERE FIRST_NAME = 'Asad';