USE Atif
GO

SELECT * FROM WORKER

SELECT 
    WORKER_ID,
    FIRST_NAME,
    LAST_NAME,
    SALARY AS SALARY_BDT,
    CONVERT(Decimal(10), SALARY/120) AS SALARY_USD,
    CONVERT(VARCHAR(10), JOINING_DATE, 101) AS JOINING_DATE_FORMATED
FROM WORKER;